### ISSUE TITLE
File .solid/.session-info-interactive not found

### ISSUE THREAD

**Issue by pheyvaer** [SolidLabResearch/Bashlib#16]
I get the following error when doing an authenticated fetch to a resource. The output of the fetch is correct though.
```shell
(node:55610) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/pheyvaer/.solid/.session-info-interactive'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1529:35)
    at /Users/pheyvaer/Development/solid/Bashlib/bashlib/css/dist/utils/util.js:196:34
    at step (/Users/pheyvaer/Development/solid/Bashlib/bashlib/css/dist/utils/util.js:33:23)
    at Object.next (/Users/pheyvaer/Development/solid/Bashlib/bashlib/css/dist/utils/util.js:14:53)
    at fulfilled (/Users/pheyvaer/Development/solid/Bashlib/bashlib/css/dist/utils/util.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I also get an error in the browser after giving consent (after logging in). The browser is trying to load a page from a server on localhost, but can't reach it.

**Comment by Dexagod** [comment]
I'm reworking the token and session management atm.
Seems like there are some checks missing there, which I'll include in the next iteration.
Thanks for the notice!

**Comment by pheyvaer** [comment]
Ok! But why already close this issue though, considering it's not fixed yet?

**Comment by Dexagod** [comment]
Think I accidentally hit comment and close instead of comment

**Comment by Dexagod** [comment]
File is generated on running the program now.
Browser keeping the tab open is normal, it can open a window for authenticating a session but not close it (afaik) from the NodeJS environment
